Prodavnica zdrave hrane/WebApplication15/WebApplication15/Controllers/KorpaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication15.Models;
using System.Data.Entity;

namespace WebApplication15.Controllers
{
    public class KorpaController : Controller
    {
        // GET: Korpa
        ProdavnicaEntities db = new ProdavnicaEntities();
        public ActionResult Index()
        {
            return View();
        }
        private int Postoji(int id)
        {
            List<Item> korpa = (List<Item>)Session["korpa"];
            for (int i = 0; i < korpa.Count; i++)
                if (korpa[i].Proizvodi.ProizvodID == id)
                    return i;
            return -1;
        }
        public ActionResult Izbaci(int id)
        {
            int index = Postoji(id);
            List<Item> korpa = (List<Item>)Session["korpa"];
            korpa.RemoveAt(index);
            Session["korpa"] = korpa;
            return View("Cart");
        }
        
        public ActionResult Kupi(int id)
        {
           
            if (Session["korpa"] == null)
            {
                List<Item> korpa = new List<Item>();
                korpa.Add(new Item(db.ProdavnicaProizvodis.Find(id), 1));
                Session["korpa"] = korpa;
               
            }
            else
            {
                List<Item> korpa = (List<Item>)Session["korpa"];
                int index = Postoji(id);
                if (index == -1)
                    korpa.Add(new Item(db.ProdavnicaProizvodis.Find(id), 1));
                else
                    korpa[index].Kolicina++;
                Session["korpa"] = korpa;
                
                
            }
            return View("Cart");
            
        }
    }
}

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Controllers/ProizvodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication15.Models;
using System.Data.Entity;
using System.IO;

namespace WebApplication15.Controllers
{
    public class ProizvodController : Controller
    {
        // GET: Proizvod
        public ActionResult Index(string searching,string SortOrder)
        {
            using(ProdavnicaEntities db=new ProdavnicaEntities())
            {
                return View(db.ProdavnicaProizvodis.Where(x => x.Ime.Contains(searching) || searching == null).ToList());
            }
        }
        public ActionResult AdminProdavnica(string searching, string SortOrder)
        {
            using (ProdavnicaEntities db = new ProdavnicaEntities())
            {
                return View(db.ProdavnicaProizvodis.Where(x => x.Ime.Contains(searching) || searching == null).ToList());
            }
        }
        public ActionResult AdminMagacin(string searching, string SortOrder)
        {
            using (ProdavnicaEntities db = new ProdavnicaEntities())
            {
                return View(db.MagacinProizvodis.Where(x => x.Ime.Contains(searching) || searching == null).ToList());
            }
        }
        public ActionResult Lista(string searching, string SortOrder)
        {
            using (ProdavnicaEntities db = new ProdavnicaEntities())
            {
                return View(db.ProdavnicaProizvodis.Where(x => x.Ime.Contains(searching) || searching == null).ToList());
            }
        }
        public ActionResult Lista2(string searching, string SortOrder)
        {
            using (ProdavnicaEntities db = new ProdavnicaEntities())
            {
                return View(db.ProdavnicaProizvodis.Where(x => x.Ime.Contains(searching) || searching == null).ToList());
            }
        }
        public ActionResult Create()
        {
            
                return View();
            
        }
        [HttpPost]
        public ActionResult Create(ProdavnicaProizvodi proizvod)
        {
            try
            {
                using(ProdavnicaEntities db=new ProdavnicaEntities())
                {
                    db.ProdavnicaProizvodis.Add(proizvod);
                    db.SaveChanges();
                }
                return RedirectToAction("AdminProdavnica");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            using(ProdavnicaEntities db=new ProdavnicaEntities())
            {
                return View(db.ProdavnicaProizvodis.Where(x=>x.ProizvodID==id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult Edit(int id,ProdavnicaProizvodi proizvodi)
        {
            try
            {
                using(ProdavnicaEntities db=new ProdavnicaEntities())
                {
                    db.Entry(proizvodi).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("AdminProdavnica");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            using (ProdavnicaEntities db=new ProdavnicaEntities())
            {
                return View(db.ProdavnicaProizvodis.Where(x => x.ProizvodID == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult Delete(int id,FormCollection collection)
        {
            try
            {
                using(ProdavnicaEntities db=new ProdavnicaEntities())
                {
                    ProdavnicaProizvodi proizvod = db.ProdavnicaProizvodis.Where(x => x.ProizvodID == id).FirstOrDefault();
                    db.ProdavnicaProizvodis.Remove(proizvod);
                    db.SaveChanges();
                }
                return RedirectToAction("AdminProdavnica");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult CreateMagacin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateMagacin(MagacinProizvodi proizvod)
        {
            try
            {
                using (ProdavnicaEntities db = new ProdavnicaEntities())
                {
                    db.MagacinProizvodis.Add(proizvod);
                    db.SaveChanges();
                }
                return RedirectToAction("AdminMagacin");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult EditMagacin(int id)
        {
            using (ProdavnicaEntities db = new ProdavnicaEntities())
            {
                return View(db.MagacinProizvodis.Where(x => x.ProizvodID == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult EditMagacin(int id, MagacinProizvodi proizvodi)
        {
            try
            {
                using (ProdavnicaEntities db = new ProdavnicaEntities())
                {
                    db.Entry(proizvodi).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("AdminMagacin");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult DeleteMagacin(int id)
        {
            using (ProdavnicaEntities db = new ProdavnicaEntities())
            {
                return View(db.MagacinProizvodis.Where(x => x.ProizvodID == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult DeleteMagacin(int id, FormCollection collection)
        {
            try
            {
                using (ProdavnicaEntities db = new ProdavnicaEntities())
                {
                    MagacinProizvodi proizvod = db.MagacinProizvodis.Where(x => x.ProizvodID == id).FirstOrDefault();
                    db.MagacinProizvodis.Remove(proizvod);
                    db.SaveChanges();
                }
                return RedirectToAction("AdminMagacin");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Prebaci(int id)
        {
            using (ProdavnicaEntities db = new ProdavnicaEntities())
            {
                return View(db.MagacinProizvodis.Where(x => x.ProizvodID == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult Prebaci(int id, ProdavnicaProizvodi proizvodi)
        {
            try
            {
                using (ProdavnicaEntities db = new ProdavnicaEntities())
                {
                    db.ProdavnicaProizvodis.Add(proizvodi);
                    db.SaveChanges();
                    MagacinProizvodi proizvod = db.MagacinProizvodis.Where(x => x.ProizvodID == id).FirstOrDefault();
                    db.MagacinProizvodis.Remove(proizvod);
                    db.SaveChanges();
                }

                return RedirectToAction("AdminMagacin");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Dobavljac()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dobavljac(string text)
        {
            string path = Server.MapPath("~/Dobavljac/Dobavljac.txt");
            using (StreamWriter sw = System.IO.File.CreateText(path))
            {
                sw.WriteLine(text);
            }
            return RedirectToAction("AdminProdavnica");
        }
        public ActionResult PorukaAdminu()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PorukaAdminu(string text)
        {
            string path = Server.MapPath("~/Dobavljac/KorisniciPoruke.txt");
            string line = "--------------------------------------";
            using (StreamWriter sw = System.IO.File.AppendText(path))
            {
                sw.WriteLine(line);
                sw.WriteLine(text);
            }
            return RedirectToAction("Index");
        }

    }
}

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Views/Proizvod/AdminMagacin.cshtml
@model IEnumerable<WebApplication15.Models.MagacinProizvodi>

@{
                /**/

                /**/

                ViewBag.Title = "Proizvodi";

                if (Session["Ime"] == null)
                {
                    <p>Ulogujte se!</p>
                    Response.Redirect("~/Korisnik/Login");
                }
}
<h3 hidden="hidden">Korisnik: @Session["Ime"].ToString()</h3>
<h3 hidden="hidden">Racun: @Session["Racun"].ToString()</h3>
<style>
    body {
        background-color: greenyellow;
    }

    .odjava {
        border: 4px solid black;
        background-color: white;
        width: 80px;
        float: right;
        color: black;
    }
</style>
<body>
    <div class="odjava">
        <a href="/Korisnik/logOut"><font color="black">Odjavi se</font></a>
    </div>
    <div class="jumbotron">

        <h2>Proizvodi u magacinu</h2>
        @using (Html.BeginForm("AdminMagacin", "Proizvod", FormMethod.Get))
        {

            @Html.TextBox("searching")<input type="submit" value="Trazi proizvod" />
        }
        <br />

        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Ime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Proizvodjac)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Vrsta)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cena)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() == 0)
                {
                    <tr>
                        <td colspan="3" style="color:red">
                            Nema trazenog proizvoda
                        </td>
                    </tr>
                }
                else
                {



                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Proizvodjac)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Vrsta)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cena)
                            </td>
                            <td>

                                @Html.ActionLink("Izmeni", "EditMagacin", new { id = item.ProizvodID }) |

                                @Html.ActionLink("Prebaci u prodavnicu", "Prebaci", new { id = item.ProizvodID }) |

                                @Html.ActionLink("Obrisi", "DeleteMagacin", new { id = item.ProizvodID }, null)

                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @Html.ActionLink("Dodaj novi", "CreateMagacin", new { }) |
        @Html.ActionLink("Vrati se ", "AdminProdavnica")
    </div>
</body>

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Views/Proizvod/AdminProdavnica.cshtml
@model IEnumerable<WebApplication15.Models.ProdavnicaProizvodi>

@{
    /**/

    ViewBag.Title = "Proizvodi";

    if (Session["Ime"] == null)
    {
        <p>Ulogujte se!</p>
        Response.Redirect("~/Korisnik/Login");
    }
}
        <style>
            body {
                background-color: greenyellow;
            }

            .odjava {
                border: 4px solid black;
                background-color: white;
                width: 80px;
                float: right;
                color: black;
            }
        </style>
<body>
<h3 hidden="hidden">Korisnik: @Session["Ime"].ToString()</h3>
<h3 hidden="hidden">Racun: @Session["Racun"].ToString()</h3>

<div class="jumbotron">
    <div class="odjava">
        <a href="/Korisnik/logOut"><font color="black">Odjavi se</font></a>
    </div>

    <h2>Nasi proizvodi</h2>
    @using (Html.BeginForm("AdminProdavnica", "Proizvod", FormMethod.Get))
    {

        @Html.TextBox("searching")<input type="submit" value="Trazi proizvod" />
       
    }
    <br />

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Ime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Proizvodjac)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vrsta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cena)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="3" style="color:red">
                        Nema trazenog proizvoda
                    </td>
                </tr>
            }
            else
            {



                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Proizvodjac)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Vrsta)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cena)
                        </td>
                        <td>

                            @Html.ActionLink("Izmeni", "Edit", new { id = item.ProizvodID }) |

                            @Html.ActionLink("Obrisi", "Delete", new { id = item.ProizvodID }, null) -->

                        </td>
                    </tr>

                }
                <tr>
                    <td>
                        @Html.ActionLink("Dodaj novi", "Create", new { })
                    </td>
                    <td>
                        @Html.ActionLink("Magacin", "AdminMagacin")
                    </td>
                    <td>
                        @Html.ActionLink("Storniraj racun", "Korisnici", "Korisnik")
                    </td>
                    <td>
                        @Html.ActionLink("Dobavljac", "Dobavljac")
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
    </body>

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Views/Proizvod/Create.cshtml
@model WebApplication15.Models.ProdavnicaProizvodi

@{
    ViewBag.Title = "Create";
}
<style>
    body{
        background-color:greenyellow;
    }
    .odjava {
        border: 4px solid black;
        background-color: white;
        width: 80px;
        float: right;
        color: black;
    }
</style>
<body>
    <div class="odjava">
        <a href="/Korisnik/logOut"><font color="black">Odjavi se</font></a>
    </div>
    <div class="jumbotron">

        <h2>Dodajte novi proizvod u prodavnicu</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Proizvodjac, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Proizvodjac, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Proizvodjac, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Vrsta, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Vrsta, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Vrsta, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Dodaj proizvod" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Vrati se nazad", "AdminProdavnica")

        </div>
    </div>
</body>

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Views/Proizvod/Dobavljac.cshtml
@model IEnumerable<WebApplication15.Models.ProdavnicaProizvodi>
@using (Html.BeginForm("Dobavljac", "Proizvod", FormMethod.Post))
{
    <style>
        body {
            background-color: greenyellow;
        }

        .odjava {
            border: 4px solid black;
            background-color: white;
            width: 80px;
            float: right;
            color: black;
        }
    </style>
    <body>
        <div class="odjava">
            <a href="/Korisnik/logOut"><font color="black">Odjavi se</font></a>
        </div>
        <div class="jumbotron">

            <textarea rows="4" cols="50" name="text" id="txtText">
</textarea>
            <div>
            <input type="submit" value="Salji dobavljacu" />
                </div><br />
            <div>
                @Html.ActionLink("Vrati se ", "AdminProdavnica")
            </div>
        </div>
    </body>

}

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Views/Proizvod/Index.cshtml
@model IEnumerable<WebApplication15.Models.ProdavnicaProizvodi>

@{
    /**/

    ViewBag.Title = "Proizvodi";

    if (Session["Ime"] == null)
    {
        <p>Ulogujte se!</p>
        Response.Redirect("~/Korisnik/Login");
    }
}
<style>
    body {
        background-image: url("/Slike/3.jpg");
    }

    .odjava {
        border: 4px solid black;
        background-color: white;
        width: 80px;
        float: right;
        color: black;
      
    }
</style>
<body>
<div class="odjava" >
    <a href="/Korisnik/logOut"><font color="black">Odjavi se</font></a>
</div>
<div class="jumbotron">
<h3>Korisnik: @Session["Ime"].ToString()</h3>
<h3>Racun: @Session["Racun"].ToString()</h3>
    </div>

<div class="jumbotron">
    <h2>Nasi proizvodi</h2>
    @using (Html.BeginForm("Index", "Proizvod", FormMethod.Get))
    {

        @Html.TextBox("searching")<input type="submit" value="Trazi proizvod" />
    }
    <br />

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Ime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Proizvodjac)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vrsta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cena)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="3" style="color:red">
                        Nema trazenog proizvoda
                    </td>
                </tr>
            }
            else
            {



                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Proizvodjac)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Vrsta)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cena)
                        </td>
                        <td>

                            @Html.ActionLink("Kupi", "Kupi", "Korpa", new { id = item.ProizvodID }, null)
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    
        @Html.ActionLink("Posalji poruku", "PorukaAdminu")
    
</div>
    </body>

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Views/Proizvod/Lista.cshtml
@model IEnumerable<WebApplication15.Models.ProdavnicaProizvodi>

@{
    /**/

    ViewBag.Title = "Proizvodi";

    
}


<style>
    body{
        background-color:greenyellow;
    }
    .logovanje {
        border: 4px solid black;
        background-color: white;
        width: 80px;
        float: right;
        color: black;
    }
    .registracija {
        border: 4px solid black;
        background-color: white;
        width: 80px;
        float: right;
        color: black;
    }
    </style>
<body>
    <div class="logovanje">
        <a href="/Korisnik/login"><font color="black">Logovanje</font></a>
    </div>
    <div class="registracija">
        <a href="/Korisnik/AddOrEdit"><font color="black">Registracija</font></a>
    </div>
    <h2>Nasi posni proizvodi</h2>
    @using (Html.BeginForm("Lista", "Proizvod", FormMethod.Get))
    {

        @Html.TextBox("searching")<input type="submit" value="Search" />
    }
    <br />
    <div class="jumbotron">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Ime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Proizvodjac)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vrsta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cena)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="3" style="color:red">
                        Nema trazenog proizvoda
                    </td>
                </tr>
            }
            else
            {



                foreach (var item in Model)
                {
                    if (item.Vrsta == "posno")
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Proizvodjac)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Vrsta)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cena)
                            </td>
                            <td>

                                @Html.ActionLink("Kupi", "login", "korisnik")
                            </td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
        </div>
</body>

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Views/Proizvod/Lista2.cshtml
@model IEnumerable<WebApplication15.Models.ProdavnicaProizvodi>

@{
    /**/

    ViewBag.Title = "Proizvodi";


}
<style>
    body {
        background-color: greenyellow;
    }

    .logovanje {
        border: 4px solid black;
        background-color: white;
        width: 80px;
        float: right;
        color: black;
    }

    .registracija {
        border: 4px solid black;
        background-color: white;
        width: 80px;
        float: right;
        color: black;
    }
</style>

<body>
    <div class="logovanje">
        <a href="/Korisnik/login"><font color="black">Logovanje</font></a>
    </div>
    <div class="registracija">
        <a href="/Korisnik/AddOrEdit"><font color="black">Registracija</font></a>
    </div>

    <h2>Nasi mrsni proizvodi</h2>
    @using (Html.BeginForm("Lista2", "Proizvod", FormMethod.Get))
    {

        @Html.TextBox("searching")<input type="submit" value="Search" />
    }
    <br />
    <div class="jumbotron">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Ime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Proizvodjac)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Vrsta)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cena)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() == 0)
                {
                    <tr>
                        <td colspan="3" style="color:red">
                            Nema trazenog proizvoda
                        </td>
                    </tr>
                }
                else
                {



                    foreach (var item in Model)
                    {
                        if (item.Vrsta == "mrsno")
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ime)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Proizvodjac)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Vrsta)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cena)
                                </td>
                                <td>

                                    @Html.ActionLink("Kupi", "login", "korisnik")
                                </td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
 
</body>

Prodavnica zdrave hrane/WebApplication15/WebApplication15/Views/Proizvod/PorukaAdminu.cshtml
@model IEnumerable<WebApplication15.Models.ProdavnicaProizvodi>
@using (Html.BeginForm("PorukaAdminu", "Proizvod", FormMethod.Post))
{
    <style>
        body {
            background-color: greenyellow;
        }

        .odjava {
            border: 4px solid black;
            background-color: white;
            width: 80px;
            float: right;
            color: black;
        }
    </style>
    <body>
        <div class="odjava">
            <a href="/Korisnik/logOut"><font color="black">Odjavi se</font></a>
        </div>
        <div class="jumbotron">
            <p>U poruci obavezno upisati ime , prezime i email adresu </p>

            <textarea rows="4" cols="50" name="text" id="txtText">
</textarea>
            <div>
                <input type="submit" value="Posalji poruku" />
            </div><br />
            <div>
                @Html.ActionLink("Vrati se ", "Index","Proizvod")
            </div>
        </div>
    </body>

}